### ISSUE TITLE
Is this example currently supported?

### ISSUE THREAD

**Issue by pkellner** [SmartThingsCommunity/cli-example-nodejs#6]
When I do a simple 

sthelper status

I get a 401 error.  I'm confident I have my token set in my environment correctly.

**Comment by beckje01** [comment]
It should be I'll try and see what I get.

**Comment by pkellner** [comment]
Any update?

**Comment by beckje01** [comment]
Yes everything is still working with a fresh install and token. If you are getting a 401 you probably have a bad token or some kind.

**Comment by beckje01** [comment]
@pkellner any further luck?

**Comment by pkellner** [comment]
Trying again. I don't remember that I did not follow the directions before to get the token, but now when I try to follow the directions in the readme and go to the URL https://account.smartthings.com/create-token , I get a 404.  Spent last 20 minutes trying to figure out how to get a token from the docs and could not figure it out.

**Comment by pkellner** [comment]
Finally found the updated link to create a token and now it works as advertised.  Thanks.
https://account.smartthings.com/tokens/new
