### ISSUE TITLE
Timing Problem with Shades and this CLI version

### ISSUE THREAD

**Issue by pkellner** [SmartThingsCommunity/cli-example-nodejs#7]
I have Lutron shades  that work perfectly with the SmartThings IOS app.  They always go all the way  up, all the way down when I command. If I stop them from going up or down midway with a remote switch, then every time, the mobile app does exactly the right thing when I instruct the shade to go up or down agan.

With this CLI version, I've got two commands I use.

sthelper turnon "Den Den Shade"
sthelper turnoff "Den Den Shade"

which both work some of the time. The problem is that they consistently will not bring the shade all the way up or all the way down.  That is, the shade will just stop moving after it starts moving.  If I do stop the shade with the pica remote, then the shade will never finish it's up or down when instructed by the CLI here (commands above).  The mobile app works 100% of the time in this case.

In all cases, the CLI's 

Successfully sent commands 'on' to device Den Den Shade
Successfully sent commands 'off' to device Den Den Shade

is output.

As I test more, I found this also:
Once I stop the shade from opening with the pico switch, then when I repeated send CLI commands to open, nothing happens.  The events get sent as I can see in the event viewer (screen shot attached), but the shade does not move.  If I go into the mobile app, press open, the shade continues to open immediately.

[Screen Shot](https://www.dropbox.com/s/vqifxkejbuycwq7/SmartThingsScreenShot1.png?dl=0)

**Comment by pkellner** [comment]
Posted a support request also 4 days ago and no one at Samsung has responded.  Just Sayin...

**Comment by jimmyjames** [comment]
Hi @pkellner, sorry for the late reply.

It sounds like you reached out to Samsung support, which would be the right avenue to pursue. This CLI is just an illustrative example of how the APIs can be used, and it sounds like the CLI is sending the command, but the specific device is not behaving as expected or consistent with the mobile app? 

It would be good to include on the Samsung support ticket information about the mobile app as well (if using the new SmartThings app or SmartThings Classic, which OS and version).

**Comment by pkellner** [comment]
Still no response on my ticket...

**Comment by pkellner** [comment]
Sadly, my support request on the SmartThings web page has had one response where they asked me a few questions (that I answered).  Today, I have given up and this is the message Ieft on the support all.  URL here if anyone from Samsung is reading this:  https://smartthings.developer.samsung.com/support/detail?id=3161

My Final Message left on the support ticket after no responses for over 3 weeks.

> I've pretty much come to the conclusion that Samsung is not supporting this technology. If I build a product with it, as I have been working towards, your lack of customer support will destroy my reputation as you are a critical part of that solution.  I am off to seriously consider homekit, though that was clearly my second choice until it has become abundantly clear that you are not supporting your products.  Very disappointed.
